version: '3'

services:
  hacken-io-db:
    container_name: hacken_io_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "admin"
    ports:
      - "15432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    network_mode: local_default
